create table if not exists projects (
  id integer primary key generated by default as identity,
  name text not null check (name <> ''), 
  priority integer not null,
  description text,
  deliverydate date not null
);

create table if not exists tasks (
  id integer primary key generated by default as identity,
  name text not null check (name <> ''),
  done boolean,
  projectId integer references projects(id)
);

-- insert projects data
insert into projects(name, priority, description, deliverydate)
  values('Make a web app', 1, 'Using js', '2019-05-12'),
  ('Make an app', 1, 'Using DART', '2019-05-12'),
  ('Make a system', 1, 'Using C++', '2019-05-12');

-- insert tasks data
insert into tasks(name, done, projectId)
  values('Download vue.js', false, 1),
  ('Make ui', false, 1),
  ('Download flutter', false, 2),
  ('Design ui', false, 2);